import type { PlannerData } from "@/lib/planner-types";
import { calculatePurchaseAmounts, shiftDate } from "@/lib/planner-utils";

function stamp(hoursAgo: number) {
  return new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString();
}

export function buildSamplePlannerData(): PlannerData {
  const refrigerator = calculatePurchaseAmounts({
    unitPrice: 1890000,
    quantity: 1,
    paymentType: "installment",
    installmentMonths: 12,
  });
  const bed = calculatePurchaseAmounts({
    unitPrice: 690000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const desk = calculatePurchaseAmounts({
    unitPrice: 380000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const sofa = calculatePurchaseAmounts({
    unitPrice: 1250000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const coffeeMachine = calculatePurchaseAmounts({
    unitPrice: 420000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const washer = calculatePurchaseAmounts({
    unitPrice: 970000,
    quantity: 1,
    paymentType: "installment",
    installmentMonths: 10,
  });
  const wallpaperConstruction = calculatePurchaseAmounts({
    unitPrice: 850000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const kitchenLightConstruction = calculatePurchaseAmounts({
    unitPrice: 280000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const networkConstruction = calculatePurchaseAmounts({
    unitPrice: 150000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });

  return {
    funds: [
      {
        id: "fund-cash",
        name: "현금",
        amount: 12000000,
        isUsable: true,
        createdAt: stamp(120),
        updatedAt: stamp(12),
      },
      {
        id: "fund-stock",
        name: "주식",
        amount: 4500000,
        isUsable: false,
        createdAt: stamp(110),
        updatedAt: stamp(18),
      },
      {
        id: "fund-coin",
        name: "코인",
        amount: 1300000,
        isUsable: false,
        createdAt: stamp(90),
        updatedAt: stamp(24),
      },
    ],
    purchases: [
      {
        id: "purchase-refrigerator",
        status: "completed",
        room: "주방",
        category: "가전",
        name: "냉장고",
        unitPrice: 1890000,
        quantity: 1,
        paymentType: "installment",
        installmentMonths: refrigerator.installmentMonths,
        totalPrice: refrigerator.totalPrice,
        monthlyPayment: refrigerator.monthlyPayment,
        link: "https://www.example.com/refrigerator",
        note: "빌트인 라인 색상과 손잡이 방향 확인 필요",
        deliveryRequired: true,
        deliveryDate: shiftDate(2),
        constructionRequired: false,
        constructionStatus: undefined,
        constructionDate: "",
        constructionStartTime: "",
        constructionCompany: "",
        constructionTotalCost: 0,
        constructionDeposit: 0,
        constructionBalance: 0,
        createdAt: stamp(96),
        updatedAt: stamp(4),
      },
      {
        id: "purchase-bed",
        status: "completed",
        room: "안방",
        category: "가구",
        name: "침대 프레임",
        unitPrice: 690000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: bed.installmentMonths,
        totalPrice: bed.totalPrice,
        monthlyPayment: bed.monthlyPayment,
        link: "",
        note: "헤드보드 패브릭 색상은 베이지로 확정",
        deliveryRequired: true,
        deliveryDate: shiftDate(-1),
        constructionRequired: false,
        constructionStatus: undefined,
        constructionDate: "",
        constructionStartTime: "",
        constructionCompany: "",
        constructionTotalCost: 0,
        constructionDeposit: 0,
        constructionBalance: 0,
        createdAt: stamp(80),
        updatedAt: stamp(7),
      },
      {
        id: "purchase-desk",
        status: "completed",
        room: "컴퓨터방",
        category: "가구",
        name: "전동 책상",
        unitPrice: 380000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: desk.installmentMonths,
        totalPrice: desk.totalPrice,
        monthlyPayment: desk.monthlyPayment,
        link: "https://www.example.com/desk",
        note: "상판 깊이 80cm 제품으로 선택",
        deliveryRequired: true,
        deliveryDate: shiftDate(7),
        constructionRequired: false,
        constructionStatus: undefined,
        constructionDate: "",
        constructionStartTime: "",
        constructionCompany: "",
        constructionTotalCost: 0,
        constructionDeposit: 0,
        constructionBalance: 0,
        createdAt: stamp(70),
        updatedAt: stamp(8),
      },
      {
        id: "purchase-sofa",
        status: "planned",
        room: "거실",
        category: "가구",
        name: "3인용 소파",
        unitPrice: 1250000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: sofa.installmentMonths,
        totalPrice: sofa.totalPrice,
        monthlyPayment: sofa.monthlyPayment,
        link: "https://www.example.com/sofa",
        note: "반려동물 스크래치 방지 원단 우선",
        deliveryRequired: true,
        deliveryDate: shiftDate(5),
        constructionRequired: false,
        constructionStatus: undefined,
        constructionDate: "",
        constructionStartTime: "",
        constructionCompany: "",
        constructionTotalCost: 0,
        constructionDeposit: 0,
        constructionBalance: 0,
        createdAt: stamp(60),
        updatedAt: stamp(3),
      },
      {
        id: "purchase-coffee-machine",
        status: "planned",
        room: "카페방",
        category: "가전",
        name: "커피머신",
        unitPrice: 420000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: coffeeMachine.installmentMonths,
        totalPrice: coffeeMachine.totalPrice,
        monthlyPayment: coffeeMachine.monthlyPayment,
        link: "https://www.example.com/coffee-machine",
        note: "머그컵 수납 위치와 전원선 길이 체크",
        deliveryRequired: true,
        deliveryDate: shiftDate(12),
        constructionRequired: false,
        constructionStatus: undefined,
        constructionDate: "",
        constructionStartTime: "",
        constructionCompany: "",
        constructionTotalCost: 0,
        constructionDeposit: 0,
        constructionBalance: 0,
        createdAt: stamp(50),
        updatedAt: stamp(2),
      },
      {
        id: "purchase-washer",
        status: "planned",
        room: "다용도실",
        category: "가전",
        name: "세탁기",
        unitPrice: 970000,
        quantity: 1,
        paymentType: "installment",
        installmentMonths: washer.installmentMonths,
        totalPrice: washer.totalPrice,
        monthlyPayment: washer.monthlyPayment,
        link: "https://www.example.com/washer",
        note: "문 열림 방향과 배수 위치 확인",
        deliveryRequired: true,
        deliveryDate: shiftDate(18),
        constructionRequired: false,
        constructionStatus: undefined,
        constructionDate: "",
        constructionStartTime: "",
        constructionCompany: "",
        constructionTotalCost: 0,
        constructionDeposit: 0,
        constructionBalance: 0,
        createdAt: stamp(36),
        updatedAt: stamp(1),
      },
      {
        id: "purchase-wallpaper",
        status: "planned",
        room: "거실",
        category: "시공",
        name: "도배",
        unitPrice: 850000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: wallpaperConstruction.installmentMonths,
        totalPrice: wallpaperConstruction.totalPrice,
        monthlyPayment: wallpaperConstruction.monthlyPayment,
        link: "",
        note: "거실과 복도 톤 통일",
        deliveryRequired: false,
        deliveryDate: "",
        constructionRequired: true,
        constructionStatus: "scheduled",
        constructionDate: shiftDate(4),
        constructionStartTime: "09:00",
        constructionCompany: "화이트홈 인테리어",
        constructionTotalCost: 850000,
        constructionDeposit: 250000,
        constructionBalance: 600000,
        createdAt: stamp(44),
        updatedAt: stamp(3),
      },
      {
        id: "purchase-kitchen-light",
        status: "planned",
        room: "주방",
        category: "시공",
        name: "주방 조명 교체",
        unitPrice: 280000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: kitchenLightConstruction.installmentMonths,
        totalPrice: kitchenLightConstruction.totalPrice,
        monthlyPayment: kitchenLightConstruction.monthlyPayment,
        link: "",
        note: "매입등 색온도 4000K 희망",
        deliveryRequired: false,
        deliveryDate: "",
        constructionRequired: true,
        constructionStatus: "before",
        constructionDate: shiftDate(15),
        constructionStartTime: "13:30",
        constructionCompany: "밝은전기",
        constructionTotalCost: 280000,
        constructionDeposit: 100000,
        constructionBalance: 180000,
        createdAt: stamp(28),
        updatedAt: stamp(2),
      },
      {
        id: "purchase-network",
        status: "completed",
        room: "컴퓨터방",
        category: "시공",
        name: "랜선 추가 배선",
        unitPrice: 150000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: networkConstruction.installmentMonths,
        totalPrice: networkConstruction.totalPrice,
        monthlyPayment: networkConstruction.monthlyPayment,
        link: "",
        note: "책상 뒤 포트 위치 조정 완료",
        deliveryRequired: false,
        deliveryDate: "",
        constructionRequired: true,
        constructionStatus: "done",
        constructionDate: shiftDate(-6),
        constructionStartTime: "10:00",
        constructionCompany: "스마트케이블",
        constructionTotalCost: 150000,
        constructionDeposit: 150000,
        constructionBalance: 0,
        createdAt: stamp(64),
        updatedAt: stamp(16),
      },
    ],
    sellItems: [
      {
        id: "sell-sofa-table",
        name: "원목 소파 테이블",
        currentLocation: "거실",
        askingPrice: 180000,
        minimumPrice: 130000,
        sellByDate: shiftDate(5),
        status: "selling",
        platform: "당근",
        note: "생활 기스는 있지만 상판 상태는 좋아요.",
        createdAt: stamp(14),
        updatedAt: stamp(2),
      },
      {
        id: "sell-microwave-rack",
        name: "전자레인지 선반",
        currentLocation: "주방",
        askingPrice: 70000,
        minimumPrice: 50000,
        sellByDate: shiftDate(2),
        status: "planned",
        platform: "번개장터",
        note: "직접 분해해서 전달 가능",
        createdAt: stamp(10),
        updatedAt: stamp(1),
      },
      {
        id: "sell-balcony-chair",
        name: "라탄 체어 2개",
        currentLocation: "안방베란다",
        askingPrice: 120000,
        minimumPrice: 90000,
        sellByDate: shiftDate(1),
        status: "reserved",
        platform: "직거래",
        note: "주말 오후 픽업 예정",
        createdAt: stamp(8),
        updatedAt: stamp(1),
      },
      {
        id: "sell-drawer",
        name: "화이트 서랍장",
        currentLocation: "작은방",
        askingPrice: 90000,
        minimumPrice: 70000,
        sellByDate: shiftDate(-3),
        status: "completed",
        platform: "당근",
        note: "판매 완료 후 반출까지 마무리",
        createdAt: stamp(52),
        updatedAt: stamp(6),
      },
    ],
    disposalItems: [
      {
        id: "dispose-mattress",
        name: "싱글 매트리스",
        currentLocation: "작은방",
        disposalMethod: "대형 폐기물 신고",
        reservationRequired: true,
        disposalCost: 15000,
        disposalDate: shiftDate(4),
        status: "reserved",
        note: "스티커 출력 후 현관 앞 배출 예정",
        createdAt: stamp(18),
        updatedAt: stamp(2),
      },
      {
        id: "dispose-rack",
        name: "철제 선반",
        currentLocation: "작은방베란다",
        disposalMethod: "",
        reservationRequired: false,
        disposalCost: 0,
        disposalDate: shiftDate(6),
        status: "needsMethod",
        note: "분리 배출 가능한지 확인 필요",
        createdAt: stamp(12),
        updatedAt: stamp(1),
      },
      {
        id: "dispose-table-lamp",
        name: "스탠드 조명",
        currentLocation: "안방",
        disposalMethod: "소형가전 수거함",
        reservationRequired: false,
        disposalCost: 0,
        disposalDate: shiftDate(-2),
        status: "completed",
        note: "관리사무소 앞 수거함 배출 완료",
        createdAt: stamp(36),
        updatedAt: stamp(4),
      },
    ],
    moveItems: [
      {
        id: "move-cafe-supplies",
        name: "커피 용품 박스",
        currentLocation: "작은방",
        targetLocation: "주방",
        status: "sorted",
        note: "컵과 드리퍼만 따로 분류 완료",
        createdAt: stamp(16),
        updatedAt: stamp(2),
      },
      {
        id: "move-bedding",
        name: "침구류 정리 박스",
        currentLocation: "안방",
        targetLocation: "작은방",
        status: "planned",
        note: "이사 전날 저녁 이동 예정",
        createdAt: stamp(14),
        updatedAt: stamp(1),
      },
      {
        id: "move-bookshelf-items",
        name: "책장 소품",
        currentLocation: "거실",
        targetLocation: "안방베란다",
        status: "before",
        note: "버릴 것과 보관할 것부터 구분 필요",
        createdAt: stamp(10),
        updatedAt: stamp(1),
      },
      {
        id: "move-monitor-box",
        name: "모니터 박스",
        currentLocation: "작은방베란다",
        targetLocation: "작은방",
        status: "completed",
        note: "포장 후 이동 완료",
        createdAt: stamp(42),
        updatedAt: stamp(6),
      },
    ],
  };
}
