import type { PlannerData } from "@/lib/planner-types";
import { calculatePurchaseAmounts, shiftDate } from "@/lib/planner-utils";

function stamp(hoursAgo: number) {
  return new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString();
}

export function buildSamplePlannerData(): PlannerData {
  const refrigerator = calculatePurchaseAmounts({
    unitPrice: 1890000,
    quantity: 1,
    paymentType: "installment",
    installmentMonths: 12,
  });
  const bed = calculatePurchaseAmounts({
    unitPrice: 690000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const desk = calculatePurchaseAmounts({
    unitPrice: 380000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const sofa = calculatePurchaseAmounts({
    unitPrice: 1250000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const coffeeMachine = calculatePurchaseAmounts({
    unitPrice: 420000,
    quantity: 1,
    paymentType: "lump",
    installmentMonths: 0,
  });
  const washer = calculatePurchaseAmounts({
    unitPrice: 970000,
    quantity: 1,
    paymentType: "installment",
    installmentMonths: 10,
  });

  return {
    funds: [
      {
        id: "fund-cash",
        name: "현금",
        amount: 12000000,
        isUsable: true,
        createdAt: stamp(120),
        updatedAt: stamp(12),
      },
      {
        id: "fund-stock",
        name: "주식",
        amount: 4500000,
        isUsable: false,
        createdAt: stamp(110),
        updatedAt: stamp(18),
      },
      {
        id: "fund-coin",
        name: "코인",
        amount: 1300000,
        isUsable: false,
        createdAt: stamp(90),
        updatedAt: stamp(24),
      },
    ],
    purchases: [
      {
        id: "purchase-refrigerator",
        status: "completed",
        room: "주방",
        category: "가전",
        name: "냉장고",
        unitPrice: 1890000,
        quantity: 1,
        paymentType: "installment",
        installmentMonths: refrigerator.installmentMonths,
        totalPrice: refrigerator.totalPrice,
        monthlyPayment: refrigerator.monthlyPayment,
        scheduleDate: shiftDate(-2),
        link: "https://www.example.com/refrigerator",
        note: "빌트인 라인 색상과 손잡이 방향 확인 필요",
        createdAt: stamp(96),
        updatedAt: stamp(4),
      },
      {
        id: "purchase-bed",
        status: "completed",
        room: "안방",
        category: "가구",
        name: "침대 프레임",
        unitPrice: 690000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: bed.installmentMonths,
        totalPrice: bed.totalPrice,
        monthlyPayment: bed.monthlyPayment,
        scheduleDate: shiftDate(-7),
        link: "",
        note: "헤드보드 패브릭 색상은 베이지로 확정",
        createdAt: stamp(80),
        updatedAt: stamp(7),
      },
      {
        id: "purchase-desk",
        status: "completed",
        room: "컴퓨터방",
        category: "가구",
        name: "전동 책상",
        unitPrice: 380000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: desk.installmentMonths,
        totalPrice: desk.totalPrice,
        monthlyPayment: desk.monthlyPayment,
        scheduleDate: shiftDate(-3),
        link: "https://www.example.com/desk",
        note: "상판 깊이 80cm 제품으로 선택",
        createdAt: stamp(70),
        updatedAt: stamp(8),
      },
      {
        id: "purchase-sofa",
        status: "planned",
        room: "거실",
        category: "가구",
        name: "3인용 소파",
        unitPrice: 1250000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: sofa.installmentMonths,
        totalPrice: sofa.totalPrice,
        monthlyPayment: sofa.monthlyPayment,
        scheduleDate: shiftDate(5),
        link: "https://www.example.com/sofa",
        note: "반려동물 스크래치 방지 원단 우선",
        createdAt: stamp(60),
        updatedAt: stamp(3),
      },
      {
        id: "purchase-coffee-machine",
        status: "planned",
        room: "카페방",
        category: "가전",
        name: "커피머신",
        unitPrice: 420000,
        quantity: 1,
        paymentType: "lump",
        installmentMonths: coffeeMachine.installmentMonths,
        totalPrice: coffeeMachine.totalPrice,
        monthlyPayment: coffeeMachine.monthlyPayment,
        scheduleDate: shiftDate(12),
        link: "https://www.example.com/coffee-machine",
        note: "머그컵 수납 위치와 전원선 길이 체크",
        createdAt: stamp(50),
        updatedAt: stamp(2),
      },
      {
        id: "purchase-washer",
        status: "planned",
        room: "다용도실",
        category: "가전",
        name: "세탁기",
        unitPrice: 970000,
        quantity: 1,
        paymentType: "installment",
        installmentMonths: washer.installmentMonths,
        totalPrice: washer.totalPrice,
        monthlyPayment: washer.monthlyPayment,
        scheduleDate: shiftDate(9),
        link: "https://www.example.com/washer",
        note: "문 열림 방향과 배수 위치 확인",
        createdAt: stamp(36),
        updatedAt: stamp(1),
      },
    ],
    shippings: [
      {
        id: "shipping-sofa",
        itemName: "3인용 소파",
        room: "거실",
        shippingStatus: "ordered",
        expectedDate: shiftDate(5),
        note: "오전 배송 요청",
        createdAt: stamp(30),
        updatedAt: stamp(3),
      },
      {
        id: "shipping-refrigerator",
        itemName: "냉장고",
        room: "주방",
        shippingStatus: "shipping",
        expectedDate: shiftDate(2),
        note: "엘리베이터 예약 필요",
        createdAt: stamp(52),
        updatedAt: stamp(2),
      },
      {
        id: "shipping-bed",
        itemName: "침대 프레임",
        room: "안방",
        shippingStatus: "delivered",
        expectedDate: shiftDate(-1),
        note: "조립까지 완료",
        createdAt: stamp(72),
        updatedAt: stamp(12),
      },
      {
        id: "shipping-coffee-machine",
        itemName: "커피머신",
        room: "카페방",
        shippingStatus: "beforeOrder",
        expectedDate: shiftDate(12),
        note: "프로모션 기간 확인 후 주문",
        createdAt: stamp(20),
        updatedAt: stamp(1),
      },
      {
        id: "shipping-desk",
        itemName: "전동 책상",
        room: "컴퓨터방",
        shippingStatus: "ordered",
        expectedDate: shiftDate(7),
        note: "기사 방문 전 높이 체크 예정",
        createdAt: stamp(66),
        updatedAt: stamp(8),
      },
      {
        id: "shipping-washer",
        itemName: "세탁기",
        room: "다용도실",
        shippingStatus: "beforeOrder",
        expectedDate: shiftDate(18),
        note: "사다리차 필요 여부 확인",
        createdAt: stamp(16),
        updatedAt: stamp(1),
      },
    ],
    constructions: [
      {
        id: "construction-wallpaper",
        name: "도배",
        room: "거실",
        constructionStatus: "scheduled",
        constructionDate: shiftDate(4),
        cost: 850000,
        company: "화이트홈 인테리어",
        contact: "010-1234-5678",
        note: "거실과 복도 톤 통일",
        createdAt: stamp(44),
        updatedAt: stamp(3),
      },
      {
        id: "construction-kitchen-light",
        name: "주방 조명 교체",
        room: "주방",
        constructionStatus: "before",
        constructionDate: shiftDate(15),
        cost: 280000,
        company: "밝은전기",
        contact: "010-2345-6789",
        note: "매입등 색온도 4000K 희망",
        createdAt: stamp(28),
        updatedAt: stamp(2),
      },
      {
        id: "construction-bedroom-curtain",
        name: "커튼 실측",
        room: "안방",
        constructionStatus: "scheduled",
        constructionDate: shiftDate(9),
        cost: 120000,
        company: "모던패브릭",
        contact: "010-3456-7890",
        note: "암막 90% 이상",
        createdAt: stamp(40),
        updatedAt: stamp(2),
      },
      {
        id: "construction-cafe-shelf",
        name: "맞춤 선반 설치",
        room: "카페방",
        constructionStatus: "before",
        constructionDate: shiftDate(21),
        cost: 460000,
        company: "우드워크",
        contact: "010-4567-8901",
        note: "원두와 잔 수납 중심",
        createdAt: stamp(18),
        updatedAt: stamp(1),
      },
      {
        id: "construction-network",
        name: "랜선 추가 배선",
        room: "컴퓨터방",
        constructionStatus: "done",
        constructionDate: shiftDate(-6),
        cost: 150000,
        company: "스마트케이블",
        contact: "010-5678-9012",
        note: "책상 뒤 포트 위치 조정 완료",
        createdAt: stamp(64),
        updatedAt: stamp(16),
      },
      {
        id: "construction-laundry-rack",
        name: "건조대 설치",
        room: "다용도실",
        constructionStatus: "scheduled",
        constructionDate: shiftDate(11),
        cost: 190000,
        company: "생활설비팀",
        contact: "010-6789-0123",
        note: "천장 높이 재확인 필요",
        createdAt: stamp(22),
        updatedAt: stamp(1),
      },
    ],
    sellItems: [
      {
        id: "sell-sofa-table",
        name: "원목 소파 테이블",
        currentLocation: "거실",
        askingPrice: 180000,
        minimumPrice: 130000,
        sellByDate: shiftDate(5),
        status: "selling",
        platform: "당근",
        note: "생활 기스는 있지만 상판 상태는 좋아요.",
        createdAt: stamp(14),
        updatedAt: stamp(2),
      },
      {
        id: "sell-microwave-rack",
        name: "전자레인지 선반",
        currentLocation: "주방",
        askingPrice: 70000,
        minimumPrice: 50000,
        sellByDate: shiftDate(2),
        status: "planned",
        platform: "번개장터",
        note: "직접 분해해서 전달 가능",
        createdAt: stamp(10),
        updatedAt: stamp(1),
      },
      {
        id: "sell-balcony-chair",
        name: "라탄 체어 2개",
        currentLocation: "안방베란다",
        askingPrice: 120000,
        minimumPrice: 90000,
        sellByDate: shiftDate(1),
        status: "reserved",
        platform: "직거래",
        note: "주말 오후 픽업 예정",
        createdAt: stamp(8),
        updatedAt: stamp(1),
      },
      {
        id: "sell-drawer",
        name: "화이트 서랍장",
        currentLocation: "작은방",
        askingPrice: 90000,
        minimumPrice: 70000,
        sellByDate: shiftDate(-3),
        status: "completed",
        platform: "당근",
        note: "판매 완료 후 반출까지 마무리",
        createdAt: stamp(52),
        updatedAt: stamp(6),
      },
    ],
    disposalItems: [
      {
        id: "dispose-mattress",
        name: "싱글 매트리스",
        currentLocation: "작은방",
        disposalMethod: "대형 폐기물 신고",
        reservationRequired: true,
        disposalCost: 15000,
        disposalDate: shiftDate(4),
        status: "reserved",
        note: "스티커 출력 후 현관 앞 배출 예정",
        createdAt: stamp(18),
        updatedAt: stamp(2),
      },
      {
        id: "dispose-rack",
        name: "철제 선반",
        currentLocation: "작은방베란다",
        disposalMethod: "",
        reservationRequired: false,
        disposalCost: 0,
        disposalDate: shiftDate(6),
        status: "needsMethod",
        note: "분리 배출 가능한지 확인 필요",
        createdAt: stamp(12),
        updatedAt: stamp(1),
      },
      {
        id: "dispose-table-lamp",
        name: "스탠드 조명",
        currentLocation: "안방",
        disposalMethod: "소형가전 수거함",
        reservationRequired: false,
        disposalCost: 0,
        disposalDate: shiftDate(-2),
        status: "completed",
        note: "관리사무소 앞 수거함 배출 완료",
        createdAt: stamp(36),
        updatedAt: stamp(4),
      },
    ],
    moveItems: [
      {
        id: "move-cafe-supplies",
        name: "커피 용품 박스",
        currentLocation: "작은방",
        targetLocation: "주방",
        status: "sorted",
        note: "컵과 드리퍼만 따로 분류 완료",
        createdAt: stamp(16),
        updatedAt: stamp(2),
      },
      {
        id: "move-bedding",
        name: "침구류 정리 박스",
        currentLocation: "안방",
        targetLocation: "작은방",
        status: "planned",
        note: "이사 전날 저녁 이동 예정",
        createdAt: stamp(14),
        updatedAt: stamp(1),
      },
      {
        id: "move-bookshelf-items",
        name: "책장 소품",
        currentLocation: "거실",
        targetLocation: "안방베란다",
        status: "before",
        note: "버릴 것과 보관할 것부터 구분 필요",
        createdAt: stamp(10),
        updatedAt: stamp(1),
      },
      {
        id: "move-monitor-box",
        name: "모니터 박스",
        currentLocation: "작은방베란다",
        targetLocation: "작은방",
        status: "completed",
        note: "포장 후 이동 완료",
        createdAt: stamp(42),
        updatedAt: stamp(6),
      },
    ],
  };
}
